version: '3.8'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-app-cwa
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres.mhlyvycaohzrpvcihgxf:Akiaka19899!@aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres?pgbouncer=true
      - DIRECT_URL=postgresql://postgres.mhlyvycaohzrpvcihgxf:Akiaka19899!@aws-1-ap-southeast-2.pooler.supabase.com:5432/postgres
    restart: unless-stopped