version: '3.8'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-app-cwa
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
